FROM node:20-slim

WORKDIR /app

RUN npm install -g pnpm@9

COPY . .

RUN pnpm install --frozen-lockfile

ARG VITE_CLERK_PUBLISHABLE_KEY=""
ARG VITE_CLERK_PROXY_URL=""
ARG VITE_CLERK_DOMAIN=""
ARG CACHEBUST=1
ENV VITE_CLERK_PUBLISHABLE_KEY=$VITE_CLERK_PUBLISHABLE_KEY
ENV VITE_CLERK_PROXY_URL=$VITE_CLERK_PROXY_URL
ENV VITE_CLERK_DOMAIN=$VITE_CLERK_DOMAIN

RUN echo "cache-bust=$CACHEBUST" && pnpm run build

EXPOSE 8080

CMD ["pnpm", "--filter", "@workspace/api-server", "run", "start"]
